# Generated by Django 4.2.11 on 2024-03-24 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_location_street_businessprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin'), ('business', 'Business')], default='user', max_length=50),
        ),
    ]
